### ISSUE TITLE
Add other countries

### ISSUE THREAD

**Issue by serdam55** [point-platform/famfamfam-flags-wpf#1]
Hi there,

thanks for this amazing project, is possible add the following countries:

{"AQ", "Antarctica"},
//            {"BQ", "Bonaire, Sint Eustatius and Saba"},
            {"CW", "Curaçao"},
//            {"IM", "Isle of Man"},
//            {"JE", "Jersey"},
//            {"BL", "Saint Barthélemy"},
//            {"MF", "Saint Martin (French part)"},
//            {"SX", "Sint Maarten (Dutch part)"},
//            {"SS", "South Sudan"},

you've commented in the code, could you please add this country? if is not possible, could you explain how can I add this? thanks.

**Comment by drewnoakes** [comment]
The line above the ones you've quoted explain the situation:

```
// NOTE FamFamFam Flags doesn't cover these ISO 3166-1 entities
```

So although we can agree they exist according to ISO 3166-1, there are no icons in the original image set for these.

The only option would be to create these images, which isn't something I have time for right now. If you can create them and make them look like part of the original set, then we can look at adding them.

**Comment by drewnoakes** [comment]
Actually, this is also explained at the bottom of the README

**Comment by serdam55** [comment]
yes I can create the image, could you tell me which steps I need to do? thanks

**Comment by drewnoakes** [comment]
Great. If you add images to the [`FamFamFam.Flags.Wpf/Images`](https://github.com/point-platform/famfamfam-flags-wpf/tree/master/FamFamFam.Flags.Wpf/Images) folder and update `CountryData.cs`, that should be everything. You could update the README as well.

**Comment by serdam55** [comment]
sorry for the late response, I've a bit problem. I added the new image but the Application.GetResourceStream(uri); throw an IO Exception, maybe I need to set to each new image a specific build mode? Thanks.

**Comment by drewnoakes** [comment]
Great to hear you're making progress. Please check the csproj file and make sure the image you've added is set as a resource.

See here for an example:

https://github.com/point-platform/famfamfam-flags-wpf/blob/master/FamFamFam.Flags.Wpf/FamFamFam.Flags.Wpf.csproj#L30

**Comment by drewnoakes** [comment]
If you make your code available as a PR I can review it.

**Comment by serdam55** [comment]
hello, I'm not able to see the image, I also added them as resource, I uploaded my version with the image here: https://files.fm/u/mtcvtqub

This what I added with their ISO:

curacao cw
scotland gb_sct
tahiti pyf
northern ireland gb_nir
kosovo rs_km
chinese taipei tw_tpe
wales gb_wls
asia 142 
south america 019
world all

the last flag is what I founded on soccerway

**Comment by drewnoakes** [comment]
Thanks for the images:

![019](https://user-images.githubusercontent.com/350947/34922173-41a70a6e-f984-11e7-9094-e972ef81b2a4.png) ![142](https://user-images.githubusercontent.com/350947/34922174-41c6361e-f984-11e7-981f-c2dae50d2848.png) ![all](https://user-images.githubusercontent.com/350947/34922175-41e0cc2c-f984-11e7-9f95-c8da803df6cb.png) ![cw](https://user-images.githubusercontent.com/350947/34922176-41ffcd2a-f984-11e7-85be-a3e0d3daff29.png) ![gb_nir](https://user-images.githubusercontent.com/350947/34922177-42386b94-f984-11e7-9196-4bd47b610743.png) ![gb_sct](https://user-images.githubusercontent.com/350947/34922178-425aad8a-f984-11e7-8353-e8b4d1b9b2f3.png) ![gb_wls](https://user-images.githubusercontent.com/350947/34922179-4277460c-f984-11e7-8844-ea1ee3fcb0fc.png) ![pyf](https://user-images.githubusercontent.com/350947/34922180-4294fddc-f984-11e7-8bc8-d95fa5e560fd.png) ![rs_km](https://user-images.githubusercontent.com/350947/34922181-42b098e4-f984-11e7-9556-4501da616521.png) ![tw_tpe](https://user-images.githubusercontent.com/350947/34922182-42d03b40-f984-11e7-84bb-1f7ae3e91c14.png)

This library is missing the following ISO 3166-1 countries:

- `AQ` Antarctica
- `BQ` Bonaire, Sint Eustatius and Saba
- ~~~`CW` Curaçao~~~
- `IM` Isle of Man
- `JE` Jersey
- `BL` Saint Barthélemy
- `MF` Saint Martin (French part)
- `SX` Sint Maarten (Dutch part)
- `SS` South Sudan

The only one I can see in the image you've provided is Curaçao. The others are not countries according to the standard we are using here. How would you imagine including the others in the library's code?

This document might also be useful:

https://github.com/lukes/ISO-3166-Countries-with-Regional-Codes/blob/master/all/all.csv

**Comment by serdam55** [comment]
I know but I need that flag.. have you fixed the image that doesn't appear? how you did this? 'cause I'm not able to see the image added as resource, I've also edited the csproj manually, but same problem

**Comment by drewnoakes** [comment]
Yep, it seems to work.

![image](https://user-images.githubusercontent.com/350947/34945488-7abb8f4c-f9fb-11e7-9b01-05a65047d8cb.png)

I'll push up a fix that contains the Curaçao flag shortly.

**Comment by drewnoakes** [comment]
Just pushed 1.1.2 to NuGet, which contains this flag. Thanks again.

**Comment by serdam55** [comment]
no problem, could you tell me how can I display the image? which steps you've done? 'cause I can't get the flag displayed

**Comment by drewnoakes** [comment]
Do you get any flags? Can you share your code? The screenshot I pasted that shows the CW flag was taken from the sample application in this repo.

**Comment by serdam55** [comment]
this is my solution: https://files.fm/u/mtcvtqub

**Comment by drewnoakes** [comment]
Can you just paste the relevant bits here please?

**Comment by serdam55** [comment]
I doesn't change the code I only added the new image, I don't know how can I show you here the problem, you should open the solution

**Comment by serdam55** [comment]
any news?

**Comment by drewnoakes** [comment]
I don't have time to look through your solution. If you paste the relevant bits from your code here I'll take a look. Have you definitely upgraded the NuGet package version?

**Comment by serdam55** [comment]
I added this in CountryData: 

            {"142", "Asia"},
            {"019", "South America"},
            {"All", "World"},

then I inserted in Images folder the relative flags with the name defined as key in the dictionary all to lower case as the standard provided by you.

Then I compiled the app but the item with those flag are blank, only the name is displayed

**Comment by drewnoakes** [comment]
As you can see in af6caf40cccfa625381ef68c63e112a15edbe724 (and [this comment](https://github.com/point-platform/famfamfam-flags-wpf/issues/1#issuecomment-357210628)) you must also add a line to the csproj.
