### ISSUE TITLE
Can I use this library on .NET 4.8?

### ISSUE THREAD

**Issue by roboticsware** [point-platform/famfamfam-flags-wpf#3]
I installed successfully by NuGet, my projet's target is .NET 4.8.  I can't navigate to any codes in lib like CountryIdToFlagImageSourceConverter in my project and can't build also.

**Comment by drewnoakes** [comment]
Yes this should be fine on net48. Can you share the error you're seeing?

**Comment by roboticsware** [comment]
I am not sure what's the problem exactly. When I restarted the visual studio again, it worked. I'll close this. And thank you for your great library.
